# Generated by Django 4.2 on 2023-04-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='expire',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
