# Generated by Django 4.2 on 2023-04-15 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_accesskey_expire_alter_accesskey_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='access_period',
            field=models.CharField(choices=[('1D', '1D'), ('3D', '3D'), ('1W', '1W'), ('2W', '2W'), ('1M', '1M'), ('3M', '3M'), ('1Y', '1Y')], default='1D', max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('device_id', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('last_activity_ip', models.GenericIPAddressField()),
                ('last_activity_log', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.accesskey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
